name: ğŸš€ Deploy to FTP server

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@master
    - name: ğŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: s1.small.pl
        username: f1932_ick
        password: ${{ secrets.ftp_password }}
        exclude: |
          .git*
          .git*/**
          node_modules/**
          .database*
          .database/**
          media/avatar
          media/avatar/**
          media/banner
          media/banner/**
